# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bf3ac550693cead31e8550a4f395ad04dc10066a274290a165b7b762278daa112c3ee74873c9d36ae599463e2eab12a2b6d5c4e59e00e482afa58c4c691468b3

test:
  secret_key_base: 7fd0e8500ef24036b28b51220a453b7110a3dd4a497e922152b035b0405761d86d4012194be9adab7e0dae13f790220d5e558309878c79727eba423b4f2f9e0a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
